#!/usr/bin/env python3
import http.server
import socketserver
import json
import os
import re
import string
import traceback

API_KEY = os.environ.get("GROQ_API_KEY", "")
if not API_KEY:
    print("WARNING: GROQ_API_KEY is not set!")

from groq import Groq
client = Groq(api_key=API_KEY) if API_KEY else None

PORT = 8000

# ---------------------------------------------------------------------------
# FRONT SIDE — the LLM stays in charge here. This is the part you liked, so
# its behavior is unchanged aside from trimming the prompt to front-only
# concerns (it no longer needs to know anything about the back checklist).
# ---------------------------------------------------------------------------

FRONT_SYSTEM_PROMPT = """
You are a decisive Creative Director helping a customer design the FRONT of a
business card. Usually this centers on their uploaded image, but sometimes the
customer has no image and is doing a text-only front instead.

You control ONLY these fields:
- front_layout (a short description of the front layout/composition)
- style_vibe (a short description of the overall visual style)
- image_fit ("contain" or "cover")
- image_scale (a number between 0.3 and 1.0, how large the image appears)
- image_position_x ("left", "center", or "right")
- image_position_y ("top", "middle", or "bottom")
- background_mode ("extend", "white", or "solid")
- background_color (a hex color, only used when background_mode is "solid")
- has_lace_accents (true/false, decorative accents)
- image_declined (true/false — whether the customer is doing a text-only
  front with no image)

You OWN the image_declined flag — decide it yourself from the conversation:
- Set it to true the moment the customer indicates, in any wording, that
  they don't have an image or want to skip it (e.g. "I don't have one", "skip
  the image", "we're text-only", "no image for now"). When you set it true,
  don't ask for an image again — steer the conversation toward typography/text
  layout ideas instead, and let reply_to_user acknowledge the switch (e.g.
  offer bold lettering of the business name, or ask about a style they have
  in mind).
- Set it back to false if the customer later says, in any wording, that they
  do have an image after all or want to add one (e.g. "actually I do have a
  logo", "found one, hold on") — acknowledge it and invite them to upload it.
- Otherwise, keep it unchanged from the current design_spec you were given.
- The "Image uploaded" flag in the context reflects whether a file was
  actually uploaded; use it together with the customer's words, not instead
  of them.

Never mention or modify contact information or anything about the back of
the card. That is handled separately by a different system.

Always return ONLY this exact JSON shape, nothing before or after it:
{
  "reply_to_user": "a short, confident reply to the customer",
  "design_spec": {
    "front_layout": "",
    "style_vibe": "",
    "image_fit": "contain",
    "image_scale": 1.0,
    "image_position_x": "center",
    "image_position_y": "middle",
    "background_mode": "extend",
    "background_color": "#ffffff",
    "has_lace_accents": false,
    "image_declined": false
  }
}
"""

# ---------------------------------------------------------------------------
# BACK SIDE — Python owns the order and the questions. The LLM is only asked
# to interpret a single answer for a single field. This is what fixes the
# "agent forgets to ask the next question" problem: the question that gets
# asked is computed here, not generated by the model.
# ---------------------------------------------------------------------------

BACK_FIELDS = [
    {"key": "name",     "label": "your full name",        "type": "text",
     "question": "Do you want your full name on the back?"},
    {"key": "title",    "label": "a job title",           "type": "text",
     "question": "Do you want a job title on the back?"},
    {"key": "company",  "label": "a company name",        "type": "text",
     "question": "Do you want a company name on the back?"},
    {"key": "phone",    "label": "a phone number",        "type": "text",
     "question": "Do you want a phone number on the back?"},
    {"key": "email",    "label": "an email address",      "type": "text",
     "question": "Do you want an email address on the back?"},
    {"key": "website",  "label": "a website",             "type": "text",
     "question": "Do you want a website URL on the back?"},
    {"key": "address",  "label": "a physical address",    "type": "text",
     "question": "Do you want a physical address on the back?"},
    {"key": "social",   "label": "social media handles",  "type": "text",
     "question": "Do you want social media handles on the back?"},
    {"key": "qr_code",  "label": "a QR code",             "type": "bool",
     "question": "Do you want a QR code on the back?"},
    {"key": "tagline",  "label": "a tagline",             "type": "text",
     "question": "Do you want a tagline or slogan on the back?"},
    {"key": "services", "label": "a short list of services", "type": "text",
     "question": "Do you want a short list of services on the back?"},
    {"key": "cta",      "label": "a call to action",      "type": "text",
     "question": "Do you want a call-to-action, like 'Call now' or 'Visit us online'?"},
]

SKIP_WORDS = {
    "no", "nope", "skip", "none", "n/a", "na", "nah", "not needed",
    "no thanks", "no thank you", "not really", "never mind", "pass",
}
YES_WORDS = {
    "yes", "yeah", "yep", "yup", "sure", "please", "yes please",
    "of course", "definitely", "add it", "add one",
}
CONFIRM_YES_WORDS = {
    "yes", "yeah", "yep", "yup", "correct", "right", "that's right",
    "thats right", "sounds good", "perfect", "good", "confirm", "confirmed",
    "correct that's it", "yes that's right",
}
CONFIRM_NO_WORDS = {
    "no", "nope", "wrong", "incorrect", "that's wrong", "thats wrong",
    "not right", "not correct", "that's not right",
}
EDIT_TRIGGERS = [
    "change", "actually", "correct", "wrong", "fix", "edit", "instead",
    "meant", "update", "redo", "mistake", "not right",
]

FIELD_BY_KEY = {f["key"]: f for f in BACK_FIELDS}


# Common lead-in phrases people use when answering — stripped so the stored
# value is just the actual content, e.g. "yeah it's ed brown" -> "ed brown".
# Deliberately conservative: if nothing matches, the raw text is kept as-is
# rather than guessed at, so we never invent something that wasn't said.
LEAD_IN_PATTERNS = [
    r"^(yeah|yep|yup|sure|ok|okay)[,]?\s+",
    r"^(it'?s|it is|that'?s|that is|thats)\s+",
    r"^(no[,]?\s+)?(the\s+)?(name|title|company( name)?|phone( number)?|"
    r"email( address)?|website|address|social( media)?|tagline|"
    r"services?|cta|call to action)\s+is\s+",
    r"^my\s+(name|title|company( name)?)\s+is\s+",
]


def _starts_with_phrase(lower, phrase):
    """True if `lower` begins with `phrase` as whole words — not just a
    matching prefix of characters. Plain str.startswith("no") would treat
    "nonya@bidness.com" as starting with "no", which is wrong; this checks
    word-by-word instead. Each word has surrounding punctuation stripped
    first, so "no," / "no." / "no!" etc. still count as the word "no"."""
    phrase_words = phrase.split()
    words = [w.strip(string.punctuation) for w in lower.split()]
    return words[:len(phrase_words)] == phrase_words


def clean_value(raw):
    text = raw.strip()
    # Peel off a leading correction prefix like "no, ..." first (the \b
    # word boundary matters — without it this would also strip "no" off
    # the front of "nonya@bidness.com", turning it into "nya@bidness.com").
    text = re.sub(r"^(no|nope)\b[,]?\s*", "", text, flags=re.IGNORECASE).strip()
    for pattern in LEAD_IN_PATTERNS:
        match = re.match(pattern, text, flags=re.IGNORECASE)
        if match:
            text = text[match.end():].strip()
    # Strip wrapping quote marks (straight or curly) if the whole value is
    # quoted.
    text = text.strip("\"'\u201c\u201d\u2018\u2019 ")
    return text


def fallback_extract(user_message, field_type):
    """Deterministic extraction — no LLM involved. This is intentional:
    an earlier version asked an LLM to "clean up" the value, and it would
    occasionally truncate real answers (dropping words it mistook for
    filler) or, worse, invent a plausible-sounding value out of nothing
    when the message didn't actually contain one. Simple string cleanup
    can't do that — worst case it's too literal, never fabricated."""
    msg = user_message.strip()
    lower = msg.lower().strip(" .!")

    if lower in SKIP_WORDS or any(_starts_with_phrase(lower, w) for w in SKIP_WORDS):
        return {"skip": True, "value": False if field_type == "bool" else ""}

    if field_type == "bool":
        value = lower in YES_WORDS or _starts_with_phrase(lower, "yes")
        return {"skip": False, "value": value}

    return {"skip": False, "value": clean_value(msg)}


def extract_back_answer(user_message, field):
    return fallback_extract(user_message, field["type"])


def classify_confirmation(message):
    lower = message.lower().strip(" .!")
    if lower in CONFIRM_YES_WORDS or any(_starts_with_phrase(lower, w) for w in CONFIRM_YES_WORDS):
        return "yes"
    if lower in CONFIRM_NO_WORDS or any(_starts_with_phrase(lower, w) for w in CONFIRM_NO_WORDS):
        return "no"
    return "unclear"


def next_unanswered_field(contact):
    for field in BACK_FIELDS:
        if contact.get(field["key"], None) is None:
            return field
    return None


def detect_edit_request(message, contact, context_key):
    """Looks for something like 'actually, change my company name' —
    a request to correct a field that's already been answered, even if
    the conversation has since moved on to a different field."""
    lower = message.lower()
    if not any(trigger in lower for trigger in EDIT_TRIGGERS):
        return None

    for field in BACK_FIELDS:
        if field["key"] == context_key:
            continue
        if contact.get(field["key"]) is None:
            continue  # only already-answered fields can be corrected this way
        label_words = [w for w in field["label"].replace("a ", "").replace("your ", "").split() if len(w) > 3]
        if field["key"] in lower or any(w in lower for w in label_words):
            return field
    return None


def ask_for_value(field, contact):
    reply = f"Sure — what should {field['label']} be?"
    update = {
        "contact": contact,
        "pending_field": field["key"],
        "pending_stage": "await_value",
        "pending_value": None,
        "back_complete": next_unanswered_field(contact) is None,
    }
    return reply, update


def propose_confirmation(field, extraction, contact):
    if extraction.get("skip"):
        pending_value = False if field["type"] == "bool" else ""
        if field["type"] == "bool":
            reply = "Just to confirm — no QR code, correct?"
        else:
            reply = f"Just to confirm — skip {field['label']} entirely, correct?"
    else:
        value = extraction.get("value")
        pending_value = value
        if field["type"] == "bool":
            reply = f"Just to confirm — {'add' if value else 'skip'} a QR code, correct?"
        else:
            reply = f"So {field['label']} will be: {value}\n\nIs that right?"

    update = {
        "contact": contact,
        "pending_field": field["key"],
        "pending_stage": "await_confirm",
        "pending_value": pending_value,
        "back_complete": next_unanswered_field(contact) is None,
    }
    return reply, update


def commit_value(field, value, contact):
    contact[field["key"]] = value
    upcoming = next_unanswered_field(contact)
    if upcoming:
        reply = f"Locked in.\n\n{upcoming['question']}"
    else:
        reply = ("That's everything I need for the back! Want to review it, "
                  "change anything, or download your card?")
    update = {
        "contact": contact,
        "pending_field": None,
        "pending_stage": None,
        "pending_value": None,
        "back_complete": upcoming is None,
    }
    return reply, update


def clear_pending(contact, back_complete):
    return {
        "contact": contact,
        "pending_field": None,
        "pending_stage": None,
        "pending_value": None,
        "back_complete": back_complete,
    }


def handle_back_side_deterministic(user_message, current_spec):
    """Deterministic keyword-based fallback — used only if the LLM
    interpretation call fails (bad JSON, network error, timeout). Kept
    intact so the flow still works if the API has a hiccup."""
    contact = dict(current_spec.get("contact", {}) or {})
    for field in BACK_FIELDS:
        contact.setdefault(field["key"], None)

    pending_key = current_spec.get("pending_field")
    pending_stage = current_spec.get("pending_stage")
    pending_value = current_spec.get("pending_value")

    context_key = pending_key or (next_unanswered_field(contact) or {}).get("key")

    # A request to correct an already-answered field always takes priority,
    # even if we were mid-conversation about something else.
    edit_target = detect_edit_request(user_message, contact, context_key)
    if edit_target:
        return ask_for_value(edit_target, contact)

    if pending_key and pending_stage == "await_confirm":
        field = FIELD_BY_KEY[pending_key]
        intent = classify_confirmation(user_message)

        if intent == "yes":
            return commit_value(field, pending_value, contact)

        if intent == "no":
            # If they packed the correction into the same message
            # ("no, it's Coffee Shop"), use it immediately instead of
            # making them repeat themselves.
            if len(user_message.split()) > 2:
                extraction = extract_back_answer(user_message, field)
                return propose_confirmation(field, extraction, contact)
            return ask_for_value(field, contact)

        # Unclear reply — most likely they just typed the corrected value
        # directly without saying "no" first. Re-extract and re-confirm.
        extraction = extract_back_answer(user_message, field)
        return propose_confirmation(field, extraction, contact)

    if pending_key and pending_stage == "await_value":
        field = FIELD_BY_KEY[pending_key]
        extraction = extract_back_answer(user_message, field)
        return propose_confirmation(field, extraction, contact)

    target = next_unanswered_field(contact)
    if target is None:
        reply = ("Your back side has everything I need! Want to change "
                  "anything, or is it ready to download?")
        return reply, clear_pending(contact, back_complete=True)

    # The initial question is phrased as yes/no ("Do you want your full name
    # on the back?"). A bare "yes" answers that question — it isn't the
    # value itself — so ask for the actual value next instead of storing
    # the word "yes" as someone's name.
    if target["type"] == "text" and classify_confirmation(user_message) == "yes":
        return ask_for_value(target, contact)

    extraction = extract_back_answer(user_message, target)
    return propose_confirmation(target, extraction, contact)


# ---------------------------------------------------------------------------
# LLM-driven interpretation of back-side answers. Python still fully owns
# *state* (which field is being asked about, what order fields come in, what
# happens for each intent) — this only classifies what the customer meant,
# so unexpected phrasing, off-topic asides, or corrections don't break the
# flow the way keyword matching could.
# ---------------------------------------------------------------------------

BACK_INTENT_SYSTEM_PROMPT = """
You are the intent classifier for a business-card back-side detail
collector. You do NOT decide which question to ask next — a separate
system controls that. Your only job is to read the customer's most recent
message and classify what they meant, given the context you're provided.

Context you will receive as JSON:
- stage: "await_confirm" if we already extracted a value and are asking the
  customer to confirm it, otherwise "await_value"
- is_initial_yes_no_gate: true only when question_asked is phrased as a
  yes/no gate for a text field ("Do you want X on the back?") and no value
  has been requested from them yet
- field_key, field_label, field_type ("text" or "bool")
- question_asked: the exact question shown to the customer
- proposed_value: only present during "await_confirm" — the value we're
  asking them to confirm
- known_fields: object of field_key -> {label, value} for fields that
  already have a stored answer (for detecting "actually, change my X")

Respond with ONLY this JSON shape, nothing else:
{
  "intent": "provide_value" | "skip" | "confirm_yes" | "confirm_no" | "edit_other_field" | "off_topic",
  "value": "",
  "edit_field_key": null,
  "reply_to_user": ""
}

Rules:
- "provide_value": the customer supplied (or corrected) a real value for
  field_key. Put the CLEANED value in "value" (strip filler like "yeah it's",
  "my name is", surrounding quotes). For bool fields, put true/false.
- "skip": the customer doesn't want this field at all, in any wording
  ("no", "skip that", "not needed", "we're good without it", etc). Leave
  "value" empty/false.
- "confirm_yes" / "confirm_no": use ONLY when stage is "await_confirm" (are
  they agreeing/disagreeing with proposed_value) OR when
  is_initial_yes_no_gate is true and the customer gave a bare yes/no with no
  actual content (e.g. just "yes" — not "yes, John Smith", which is
  provide_value).
- "edit_other_field": the customer wants to go back and change a field
  OTHER than field_key that already appears in known_fields (e.g. "actually
  change my company name"). Set edit_field_key to that field's key.
- "off_topic": the customer asked a question, made small talk, or said
  something unrelated to answering field_key (e.g. "what's a QR code?",
  "do you do postcards too?", random chatter, confusion). Write a short,
  friendly "reply_to_user" that briefly addresses what they said, then ends
  by re-asking question_asked (verbatim or near-verbatim) so the
  conversation doesn't lose its place. Do not guess a value in this case.
- Never fabricate a value the customer didn't actually provide. If genuinely
  ambiguous, prefer "off_topic" with a clarifying reply_to_user over
  guessing.
"""


def _resolve_back_extraction(intent, value, field_type):
    """Turns an LLM intent + raw value into the {skip, value} shape the
    existing propose_confirmation/commit_value helpers expect."""
    if intent == "provide_value":
        if field_type == "bool":
            return {"skip": False, "value": bool(value)}
        return {"skip": False, "value": (value or "").strip() if isinstance(value, str) else str(value or "")}
    if intent == "skip":
        return {"skip": True, "value": False if field_type == "bool" else ""}
    if intent == "confirm_yes":
        if field_type == "bool":
            return {"skip": False, "value": True}
        return {"skip": False, "value": (value or "").strip() if isinstance(value, str) else str(value or "")}
    if intent == "confirm_no":
        return {"skip": True, "value": False if field_type == "bool" else ""}
    return None


def interpret_back_reply(user_message, contact, field, stage, pending_value, is_initial_yes_no_gate, question_asked):
    if not client:
        raise RuntimeError("GROQ_API_KEY is missing or empty")

    known_fields = {
        k: {"label": FIELD_BY_KEY[k]["label"], "value": v}
        for k, v in contact.items()
        if v is not None and k != field["key"] and k in FIELD_BY_KEY
    }

    context = {
        "stage": stage,
        "is_initial_yes_no_gate": is_initial_yes_no_gate,
        "field_key": field["key"],
        "field_label": field["label"],
        "field_type": field["type"],
        "question_asked": question_asked,
        "proposed_value": pending_value if stage == "await_confirm" else None,
        "known_fields": known_fields,
    }

    messages = [
        {"role": "system", "content": BACK_INTENT_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": f"Context: {json.dumps(context)}\n\nCustomer: {user_message}",
        },
    ]

    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=messages,
        response_format={"type": "json_object"},
        temperature=0.1,
        timeout=15,
    )

    raw = completion.choices[0].message.content.strip()
    result = json.loads(raw)

    if result.get("intent") not in {
        "provide_value", "skip", "confirm_yes", "confirm_no",
        "edit_other_field", "off_topic",
    }:
        raise ValueError("Model returned an unrecognized intent")

    return result


def handle_back_side(user_message, current_spec):
    contact = dict(current_spec.get("contact", {}) or {})
    for field in BACK_FIELDS:
        contact.setdefault(field["key"], None)

    pending_key = current_spec.get("pending_field")
    pending_stage = current_spec.get("pending_stage")
    pending_value = current_spec.get("pending_value")

    target = next_unanswered_field(contact)
    if pending_key is None and target is None:
        reply = ("Your back side has everything I need! Want to change "
                  "anything, or is it ready to download?")
        return reply, clear_pending(contact, back_complete=True)

    field_key = pending_key or target["key"]
    field = FIELD_BY_KEY[field_key]
    stage = pending_stage or "await_value"
    is_initial_yes_no_gate = pending_key is None and field["type"] == "text"
    question_asked = (
        field["question"] if is_initial_yes_no_gate
        else (f"So {field['label']} will be: {pending_value}\n\nIs that right?"
              if stage == "await_confirm"
              else f"Sure — what should {field['label']} be?")
    )

    def _reprompt(reply_text):
        update = {
            "contact": contact,
            "pending_field": field_key,
            "pending_stage": stage,
            "pending_value": pending_value,
            "back_complete": next_unanswered_field(contact) is None,
        }
        return reply_text, update

    try:
        result = interpret_back_reply(
            user_message, contact, field, stage, pending_value,
            is_initial_yes_no_gate, question_asked,
        )
    except Exception as e:
        print(f"Back-side LLM interpretation failed, using fallback: {e}")
        return handle_back_side_deterministic(user_message, current_spec)

    intent = result.get("intent")

    if intent == "edit_other_field":
        edit_key = result.get("edit_field_key")
        if edit_key in FIELD_BY_KEY and contact.get(edit_key) is not None:
            return ask_for_value(FIELD_BY_KEY[edit_key], contact)
        intent = "off_topic"

    if intent == "off_topic":
        return _reprompt(result.get("reply_to_user") or question_asked)

    if stage == "await_confirm":
        if intent == "confirm_yes":
            return commit_value(field, pending_value, contact)
        if intent == "confirm_no":
            return ask_for_value(field, contact)
        extraction = _resolve_back_extraction(intent, result.get("value"), field["type"])
        if extraction is None:
            return _reprompt(question_asked)
        return propose_confirmation(field, extraction, contact)

    # stage == "await_value"
    if is_initial_yes_no_gate and intent == "confirm_yes":
        return ask_for_value(field, contact)
    extraction = _resolve_back_extraction(intent, result.get("value"), field["type"])
    if extraction is None:
        return _reprompt(question_asked)
    return propose_confirmation(field, extraction, contact)


def handle_front_side(user_message, current_spec, image_uploaded):
    if not client:
        raise RuntimeError("GROQ_API_KEY is missing or empty")

    image_declined = bool(current_spec.get("image_declined", False))

    messages = [
        {"role": "system", "content": FRONT_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"Image uploaded: {image_uploaded}\n"
                f"Image declined: {image_declined}\n"
                f"Current design_spec: {json.dumps(current_spec)}\n\n"
                f"Customer: {user_message}"
            ),
        },
    ]

    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=messages,
        response_format={"type": "json_object"},
        temperature=0.1,
        timeout=20,
    )

    raw = completion.choices[0].message.content.strip()
    response = json.loads(raw)

    if "reply_to_user" not in response or "design_spec" not in response:
        raise ValueError("Model returned incomplete JSON")

    return response["reply_to_user"], response["design_spec"]


# ---------------------------------------------------------------------------
# CARD SIDES GATE — the very first decision, before any front/back logic.
# A closed either/or question, answered via the LLM (with a deterministic
# keyword fallback) — this decides whether the customer gets a front side
# at all. Same pattern as the back-side interpreter: Python owns the
# question and the resulting state change, the LLM only classifies intent.
# ---------------------------------------------------------------------------

SIDES_GATE_QUESTION = "Would you like a one-sided or two-sided business card?"

IMAGE_GATE_QUESTION = (
    "Do you have an image you'd like to use, or would you like a text-only "
    "design instead?"
)

SIDES_INTENT_SYSTEM_PROMPT = """
You are an intent classifier for a single either/or question in a business
card design tool: "Would you like a one-sided or two-sided business card?"

Respond with ONLY this JSON shape, nothing else:
{
  "intent": "one" | "two" | "off_topic",
  "reply_to_user": ""
}

Rules:
- "one": the customer wants a one-sided card, in any wording ("just one
  side", "one is fine", "single-sided", "1", "one please").
- "two": the customer wants a two-sided card, in any wording ("two sides",
  "double-sided", "front and back", "2", "both sides").
- "off_topic": the customer asked a question, made small talk, or said
  something that doesn't answer the one/two question. Write a short,
  friendly "reply_to_user" that briefly addresses what they said, then ends
  by asking: "%s" (verbatim). Do not guess one vs two in this case.
""" % SIDES_GATE_QUESTION

ONE_SIDE_WORDS = {
    "one", "1", "one-sided", "one sided", "single", "single-sided",
    "single sided", "just one", "one side", "just the one",
}
TWO_SIDE_WORDS = {
    "two", "2", "two-sided", "two sided", "double", "double-sided",
    "double sided", "both", "both sides", "front and back", "two sides",
}


def _sides_fallback(user_message):
    """Deterministic fallback used only if the LLM call fails."""
    lower = user_message.lower().strip(" .!")
    if lower in ONE_SIDE_WORDS or any(_starts_with_phrase(lower, w) for w in ONE_SIDE_WORDS):
        return {"intent": "one", "reply_to_user": ""}
    if lower in TWO_SIDE_WORDS or any(_starts_with_phrase(lower, w) for w in TWO_SIDE_WORDS):
        return {"intent": "two", "reply_to_user": ""}
    return {"intent": "off_topic", "reply_to_user": SIDES_GATE_QUESTION}


def interpret_sides_reply(user_message):
    if not client:
        raise RuntimeError("GROQ_API_KEY is missing or empty")

    messages = [
        {"role": "system", "content": SIDES_INTENT_SYSTEM_PROMPT},
        {"role": "user", "content": f"Customer: {user_message}"},
    ]
    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=messages,
        response_format={"type": "json_object"},
        temperature=0.1,
        timeout=15,
    )
    raw = completion.choices[0].message.content.strip()
    result = json.loads(raw)
    if result.get("intent") not in {"one", "two", "off_topic"}:
        raise ValueError("Model returned an unrecognized intent")
    return result


def handle_sides_gate(user_message, current_spec):
    try:
        result = interpret_sides_reply(user_message)
    except Exception as e:
        print(f"Sides-gate LLM interpretation failed, using fallback: {e}")
        result = _sides_fallback(user_message)

    intent = result.get("intent")
    spec_update = dict(current_spec)

    if intent == "off_topic":
        spec_update["card_sides"] = None
        reply = result.get("reply_to_user") or SIDES_GATE_QUESTION
        return reply, spec_update

    if intent == "one":
        spec_update["card_sides"] = "one"
        contact = dict(current_spec.get("contact", {}) or {})
        for field in BACK_FIELDS:
            contact.setdefault(field["key"], None)
        spec_update["contact"] = contact
        spec_update["pending_field"] = None
        spec_update["pending_stage"] = None
        spec_update["pending_value"] = None
        spec_update["back_complete"] = False
        reply = (
            "Got it — one-sided it is. That means this one side is the "
            f"whole card, so let's fill in the details.\n\n{BACK_FIELDS[0]['question']}"
        )
        return reply, spec_update

    # intent == "two"
    spec_update["card_sides"] = "two"
    reply = f"Two-sided it is. {IMAGE_GATE_QUESTION}"
    return reply, spec_update


# ---------------------------------------------------------------------------
# IMAGE GATE — the second closed-ended decision, reached once card_sides ==
# "two". Same pattern as the sides gate: Python owns the question and the
# resulting state, the LLM only classifies intent, and anything ambiguous
# gets a clarifying re-ask instead of a guess. This is what fixes the
# "agent gives up and moves on" failure mode — a double-negative like "no,
# I don't want to skip it" was previously handled inside the big open-ended
# creative chat and got misread as declining the image.
# ---------------------------------------------------------------------------

IMAGE_INTENT_SYSTEM_PROMPT = """
You are an intent classifier for a single either/or question in a business
card design tool: "Do you have an image you'd like to use, or would you like
a text-only design instead?"

Respond with ONLY this JSON shape, nothing else:
{
  "intent": "has_image" | "no_image" | "off_topic",
  "reply_to_user": ""
}

Rules:
- "has_image": the customer has an image (logo, photo, graphic, etc.) and
  wants to use it, in any wording ("yes I have one", "I'll upload it", "I
  have a logo", "yeah", "of course" in response to being asked if they want
  to use an image).
  IMPORTANT — watch for double negatives: "no, I don't want to skip it"
  means they do NOT want to skip the image, i.e. they want to use it — that
  is "has_image", not "no_image". Read the whole sentence, don't just react
  to the first word.
- "no_image": the customer doesn't have an image, or wants to skip it and go
  text-only, in any wording ("no image", "no logo", "skip it", "text-only
  please", "don't have one").
- "off_topic": the customer asked a question, made small talk, expressed
  confusion, or said something that doesn't clearly answer the question
  (e.g. "do I have an image?", "what counts as an image", "does it
  matter?"). Write a short, friendly "reply_to_user" that briefly
  clarifies/answers what they said, then ends by asking: "Do you have an
  image you'd like to use, or would you like a text-only design instead?"
  (verbatim). Never guess has_image/no_image here — if there's any doubt,
  use off_topic.
"""

HAS_IMAGE_WORDS = {
    "yes", "yeah", "yep", "yup", "i have one", "i have a logo",
    "i have an image", "i'll upload it", "ill upload it", "sure", "of course",
}
NO_IMAGE_WORDS = {
    "no", "nope", "no logo", "no image", "skip it", "skip", "text only",
    "text-only", "dont have one", "don't have one", "i don't have one",
    "none",
}


def _image_fallback(user_message):
    """Deterministic fallback used only if the LLM call fails. Simple
    keyword matching can't reliably resolve double negatives, so anything
    containing an explicit negation word alongside "skip" is treated as
    off_topic rather than guessed at."""
    lower = user_message.lower().strip(" .!")
    if "skip" in lower and any(neg in lower for neg in ("don't", "dont", "not", "no ")):
        # e.g. "no I don't want to skip it" — too risky to guess, ask again.
        return {"intent": "off_topic", "reply_to_user": IMAGE_GATE_QUESTION}
    if lower in HAS_IMAGE_WORDS or any(_starts_with_phrase(lower, w) for w in HAS_IMAGE_WORDS):
        return {"intent": "has_image", "reply_to_user": ""}
    if lower in NO_IMAGE_WORDS or any(_starts_with_phrase(lower, w) for w in NO_IMAGE_WORDS):
        return {"intent": "no_image", "reply_to_user": ""}
    return {"intent": "off_topic", "reply_to_user": IMAGE_GATE_QUESTION}


def interpret_image_reply(user_message):
    if not client:
        raise RuntimeError("GROQ_API_KEY is missing or empty")

    messages = [
        {"role": "system", "content": IMAGE_INTENT_SYSTEM_PROMPT},
        {"role": "user", "content": f"Customer: {user_message}"},
    ]
    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=messages,
        response_format={"type": "json_object"},
        temperature=0.1,
        timeout=15,
    )
    raw = completion.choices[0].message.content.strip()
    result = json.loads(raw)
    if result.get("intent") not in {"has_image", "no_image", "off_topic"}:
        raise ValueError("Model returned an unrecognized intent")
    return result


def handle_image_gate(user_message, current_spec):
    try:
        result = interpret_image_reply(user_message)
    except Exception as e:
        print(f"Image-gate LLM interpretation failed, using fallback: {e}")
        result = _image_fallback(user_message)

    intent = result.get("intent")
    spec_update = dict(current_spec)

    if intent == "off_topic":
        spec_update["image_declined"] = None
        reply = result.get("reply_to_user") or IMAGE_GATE_QUESTION
        return reply, spec_update

    if intent == "has_image":
        spec_update["image_declined"] = False
        reply = "Great — go ahead and upload it whenever you're ready."
        return reply, spec_update

    # intent == "no_image"
    spec_update["image_declined"] = True
    spec_update["front_layout"] = "Text-only front — no image"
    reply = ("No problem — we'll do a text-only front instead. Want your "
              "business name set in bold lettering as the centerpiece, or "
              "would you like to describe a style you have in mind?")
    return reply, spec_update


class Handler(http.server.SimpleHTTPRequestHandler):
    def do_POST(self):
        if self.path != "/api/chat":
            self.send_error(404)
            return

        current_spec = {}
        try:
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            data = json.loads(body.decode("utf-8"))

            user_message = data.get("message", "").strip()
            current_spec = data.get("state", {}) or {}
            image_uploaded = data.get("image_uploaded", False)
            front_locked = data.get("front_locked", False)
            card_sides = current_spec.get("card_sides")
            image_declined = current_spec.get("image_declined")

            print(f"\n--- New request ---")
            print(f"card_sides: {card_sides}, image_declined: {image_declined}, front_locked: {front_locked}")
            print(f"User: {user_message}")

            if card_sides is None:
                # Nothing decided yet — this is always the first question,
                # ahead of any front/back logic.
                reply, spec_update = handle_sides_gate(user_message, current_spec)
            elif card_sides == "one":
                # One-sided cards never have a front/image design — every
                # message from here on is back-side detail collection.
                reply, spec_update = handle_back_side(user_message, current_spec)
            elif front_locked:
                reply, spec_update = handle_back_side(user_message, current_spec)
            elif image_declined is None:
                # Two-sided, but we don't yet know if there's an image —
                # resolve that closed question before any creative chat.
                reply, spec_update = handle_image_gate(user_message, current_spec)
            else:
                reply, spec_update = handle_front_side(
                    user_message, current_spec, image_uploaded
                )

            response = {"reply_to_user": reply, "design_spec": spec_update}

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(response).encode("utf-8"))

        except Exception as e:
            print("\n========== ERROR ==========")
            traceback.print_exc()
            print("===========================\n")

            error = {
                "reply_to_user": f"Error: {str(e)}",
                "design_spec": current_spec,
            }
            self.send_response(500)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(error).encode("utf-8"))

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()


class ThreadingHTTPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    daemon_threads = True
    allow_reuse_address = True


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)) or ".")
    with ThreadingHTTPServer(("", PORT), Handler) as httpd:
        print(f"Server running -> http://localhost:{PORT}")
        httpd.serve_forever()
